In [175]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from sklearn.linear_model import LinearRegression

In [111]:
df = pd.read_csv('data/cars.csv')

In [112]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [113]:
df.isna().sum()

brand            0
km_driven        0
fuel             0
owner            0
selling_price    0
dtype: int64

In [114]:
df.brand.nunique()

32

In [115]:
df.brand.unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [116]:
df.brand.value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [117]:
df.fuel.nunique()

4

In [118]:
df.fuel.unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [119]:
df.fuel.value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [120]:
df.owner.unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth & Above Owner', 'Test Drive Car'], dtype=object)

In [121]:
df.owner.value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

### One Hot Encoding using Pandas

In [122]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

brand  km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  \
0      Maruti     145500         450000         0            1         0   
1       Skoda     120000         370000         0            1         0   
2       Honda     140000         158000         0            0         0   
3     Hyundai     127000         225000         0            1         0   
4      Maruti     120000         130000         0            0         0   
...       ...        ...            ...       ...          ...       ...   
8123  Hyundai     110000         320000         0            0         0   
8124  Hyundai     119000         135000         0            1         0   
8125   Maruti     120000         382000         0            1         0   
8126     Tata      25000         290000         0            1         0   
8127     Tata      25000         290000         0            1         0   

      fuel_Petrol  owner_First Owner  owner_Fourth & Above Owner  \
0               0                  1                           0   
1               0                  0                           0   
2               1                  0                           0   
3               0                  1                           0   
4               1                  1                           0   
...           ...                ...                         ...   
8123            1                  1                           0   
8124            0                  0                           1   
8125            0                  1                           0   
8126            0                  1                           0   
8127            0                  1                           0   

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner  
0                      0                     0                  0  
1                      1                     0                  0  
2                      0                     0                  1  
3                      0                     0                  0  
4                      0                     0                  0  
...                  ...                   ...                ...  
8123                   0                     0                  0  
8124                   0                     0                  0  
8125                   0                     0                  0  
8126                   0                     0                  0  
8127                   0                     0                  0  

[8128 rows x 12 columns]

In [123]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [124]:
X_train

brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [125]:
X_test

brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner
...        ...        ...     ...           ...
1537    Maruti      50000  Diesel   First Owner
6153    Maruti     111000  Petrol   First Owner
7954    Maruti      40000  Petrol   First Owner
2310   Hyundai      80000  Petrol  Second Owner
712    Hyundai      50000  Diesel   First Owner

[1626 rows x 4 columns]

In [126]:
y_train

5571    1150000
2038    1689999
2957     580000
7618     150000
6684     320000
         ...   
3606     620000
5704     335000
6637     450000
2575     651000
7336    1160000
Name: selling_price, Length: 6502, dtype: int64

In [127]:
y_test

606      200000
7575     750000
7705    2000000
4305      52000
2685     509999
         ...   
1537     650000
6153     220000
7954     320000
2310     150000
712      715000
Name: selling_price, Length: 1626, dtype: int64

### One Hot Encoding Using sklearn

In [128]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [129]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']])

In [130]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [131]:
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [132]:
X_test_new

array([[0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [133]:
X_train[['brand', 'km_driven']].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], dtype=object)

In [134]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

In [135]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new)).shape

(6502, 9)

### One hot Encoding with Top Categories

In [136]:
counts = df.brand.value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [137]:
df.brand.nunique()
threshold = 100

In [138]:
repl = counts[counts <= threshold].index

In [139]:
len(repl)

20

In [96]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=int).sample(5)

BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  \
4781    0          0     0      0        1         0       0        0      0   
5504    0          0     0      0        0         0       1        0      0   
416     0          0     0      0        0         0       1        0      0   
4902    0          0     0      0        0         0       1        0      0   
866     0          0     0      0        0         0       1        0      0   

      Tata  Toyota  Volkswagen  uncommon  
4781     0       0           0         0  
5504     0       0           0         0  
416      0       0           0         0  
4902     0       0           0         0  
866      0       0           0         0

In [166]:
brand_dummies = pd.get_dummies(X_train['brand'].replace(repl, 'uncommon'), dtype=int)

In [167]:
brand_ohe = np.hstack((X_train[['km_driven']].values, X_train_new, brand_dummies))

In [168]:
brand_ohe.shape

(6502, 21)

In [160]:
brand_dummies.values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [161]:
brand_dummies.shape

(6502, 12)

In [170]:
brand_dummies2 = pd.get_dummies(X_test['brand'].replace(repl, 'uncommon'), dtype=int)

In [172]:
brand_ohe_test = np.hstack((X_test[['km_driven']].values, X_test_new, brand_dummies2))

In [173]:
brand_ohe_test.shape

(1626, 21)

In [174]:
brand_ohe_test

array([[80000,     0,     0, ...,     0,     0,     0],
       [70000,     1,     0, ...,     0,     0,     0],
       [68089,     0,     0, ...,     1,     0,     0],
       ...,
       [40000,     0,     0, ...,     0,     0,     0],
       [80000,     0,     0, ...,     0,     0,     0],
       [50000,     1,     0, ...,     0,     0,     0]])

In [176]:
X_train_lts = brand_ohe
X_test_lts = brand_ohe_test

In [177]:
reg = LinearRegression()

In [178]:
reg.fit(X_train_lts, y_train)

LinearRegression()

In [180]:
y_pred = reg.predict(X_test_lts)

In [181]:
pd.DataFrame({'y_test': y_test, 'y_pred': y_pred})

y_test         y_pred
606    200000  433847.239976
7575   750000  523024.870985
7705  2000000  934939.678717
4305    52000  209984.642862
2685   509999  468131.182091
...       ...            ...
1537   650000  686525.692577
6153   220000  313207.984673
7954   320000  457558.055468
2310   150000  189653.646976
712    715000  744138.860632

[1626 rows x 2 columns]